packages <- c("HGNChelper", "httr", "RCurl", "rjson", "stringr")
install.packages(packages, dependencies = T)

setwd("./TCGA-Assembler/")

#load Module A and Module B functions into the working space
source("./Module_A.R")
source("./Module_B.R")

#Choose breast invasive carcinoma (BRCA) as the cancer type for demo.
sCancer <- "BRCA"

#Choose several patients to form a small data set for the demo. The following are TCGA barcodes of patients.
vPatientID <- c("TCGA-A7-A13F", "TCGA-AO-A12B", "TCGA-AR-A1AP", "TCGAAR-
A1AQ", "TCGA-AR-A1AS", "TCGA-AR-A1AV", "TCGA-AR-A1AW", "TCGA-BHA0BZ",
                "TCGA-BH-A0DD", "TCGA-BH-A0DG")

#et the directory for saving the result data files that are generated by each part of the code.
sPath1 <- "./QuickStartExample/Part1_DownloadedData"
sPath2 <- "./QuickStartExample/Part2_BasicDataProcessingResult"
sPath3 <- "./QuickStartExample/Part3_AdvancedDataProcessingResult"

#we download copy number alteration (CNA) data using the following command.
path_copyNumber <- DownloadCNAData(cancerType = sCancer, assayPlatform = "cna_cnv.hg19", inputPatientIDs = vPatientID, saveFolderName = sPath1)

#Using the following command, we can download DNA methylation data generated by the Illumina Infinium HumanMethylation450 BeadChip.
path_methylation_450 <- DownloadMethylationData(cancerType = sCancer,assayPlatform = "methylation_450", inputPatientIDs = vPatientID,                 saveFolderName = sPath1)

#The following command downloads miRNA expression data.
path_miRNAExp <- DownloadmiRNASeqData(cancerType = sCancer, assayPlatform = "mir_HiSeq.hg19.mirbase20", inputPatientIDs =vPatientID, saveFolderName = sPath1)

DownloadCNAData(cancerType = 'LIHC', assayPlatform = NULL, tissueType = NULL, saveFolderName = "LIHC", outputFileName = "", inputPatientIDs = NULL)

DownloadBiospecimenClinicalData(cancerType= 'LIHC', saveFolderName = "./BiospecimenClinicalData", outputFileName = "")
